program:
  id: "demo-001"
  name: "Demo Company"
  contact: "security@demo.com"
  policy_url: "https://demo.com/security"
github:
  orgs: ["TON_PSEUDO_GITHUB"]   # ← remplace par ton pseudo pour tester
dns:
  root_domains: ["demo.com"]
  wordlist_hint: ["dev","staging","static","cdn","api"]
storage:
  providers: ["aws_s3","gcs","azure_blob"]
  naming_hints: ["demo","cdn","assets","public","static"]
